-- ═══════════════════════════════════════════════════════════════
--  PAPER RECEIPT BOOK NUMBER
--
--  The office writes a paper receipt from a pre-numbered book when a
--  parent pays. This column stores that number so a row in the system
--  can be matched to the physical slip during the end-of-day count.
--
--  It is deliberately NOT unique and NOT required:
--    • one paper receipt covers the whole payment, but a payment that
--      covers three months creates three fee_payments rows, so the same
--      book number legitimately appears on all three
--    • a clerk may leave it blank, or repeat one by mistake — neither
--      should ever block a payment from being recorded
--
--  The guaranteed-unique identifier stays receipt_number (R-000001),
--  generated by the database. This is the human's number; that is the
--  system's number. Both are searchable.
--
--  SAFE ON A LIVE DATABASE: adds one nullable column and one index.
-- ═══════════════════════════════════════════════════════════════

ALTER TABLE fee_payments
  ADD COLUMN IF NOT EXISTS receipt_book_no VARCHAR(40);

-- Looked up when reconciling against the paper book.
CREATE INDEX IF NOT EXISTS idx_fee_payments_book_no
  ON fee_payments (receipt_book_no)
  WHERE receipt_book_no IS NOT NULL;
