-- ═══════════════════════════════════════════════════════════════
--  FEE RECEIPT SERIAL NUMBERS
--
--  fee_payments.receipt_number has existed since the original schema
--  but nothing ever wrote to it — every row is NULL. The office needs a
--  serial per payment so a specific payment can be found, quoted to a
--  parent, and matched against the paper book at the end of the day.
--
--  The number is generated by the DATABASE, not the application. There
--  are six different INSERT paths in src/routes/fees.js (single month,
--  split across months, excess to debt, debt payment, and two
--  carry-forward markers); a column default is the only way to be sure
--  every real payment gets exactly one number no matter which path ran.
--
--  Carry-forward markers are NOT payments — no money changes hands —
--  so those two inserts pass receipt_number = NULL explicitly.
--
--  SAFE ON A LIVE DATABASE:
--    • adds a sequence and a column default
--    • backfills numbers onto existing payments that have none
--    • changes no amount, date, student or month on any row
-- ═══════════════════════════════════════════════════════════════

CREATE SEQUENCE IF NOT EXISTS fee_receipt_seq;

-- Widen if an older deployment created this narrower than the format needs.
ALTER TABLE fee_payments ALTER COLUMN receipt_number TYPE VARCHAR(30);

-- ── Backfill existing real payments, oldest first, so the serial order
--    matches the order money actually came in.
DO $backfill$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT id FROM fee_payments
     WHERE receipt_number IS NULL
       AND COALESCE(carried_forward, FALSE) = FALSE
     ORDER BY payment_date NULLS FIRST, id
  LOOP
    UPDATE fee_payments
       SET receipt_number = 'R-' || LPAD(nextval('fee_receipt_seq')::text, 6, '0')
     WHERE id = r.id;
  END LOOP;
END
$backfill$;

-- ── From now on every inserted row gets one automatically ──────
ALTER TABLE fee_payments
  ALTER COLUMN receipt_number
  SET DEFAULT 'R-' || LPAD(nextval('fee_receipt_seq')::text, 6, '0');

-- One receipt number, one payment. (schema.sql declared this UNIQUE, but
-- deployments built up from migrations may not have it.)
CREATE UNIQUE INDEX IF NOT EXISTS fee_payments_receipt_uniq
  ON fee_payments (receipt_number)
  WHERE receipt_number IS NOT NULL;

-- Day-level reconciliation reads by date, so give it an index.
CREATE INDEX IF NOT EXISTS idx_fee_payments_date
  ON fee_payments (payment_date);
